//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBBAPI2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public Program()
        {
            this.Sets = new HashSet<Set>();
            this.Users = new HashSet<User>();
        }
    
        public int programid { get; set; }
        public Nullable<int> facultyid { get; set; }
        public string programname { get; set; }
    
        public virtual ICollection<Set> Sets { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
