//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBBAPI2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.Courses = new HashSet<Course>();
            this.UserCourseSections = new HashSet<UserCourseSection>();
        }
    
        public int userid { get; set; }
        public int programid { get; set; }
        public int setid { get; set; }
        public int facultyid { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string type { get; set; }
        public bool active { get; set; }
        public string phonenumber { get; set; }
        public string token { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual Program Program { get; set; }
        public virtual Set Set { get; set; }
        public virtual ICollection<UserCourseSection> UserCourseSections { get; set; }
    }
}
